module.exports = {
  API_VERSION: process.env.API_VERSION,
  COGNITO_CLIENT_SECRET: process.env.COGNITO_CLIENT_SECRET,
  COGNITO_REGION: process.env.COGNITO_REGION,
  COGNITO_POOL_ID: process.env.COGNITO_POOL_ID,
  API_VERSION: process.env.API_VERSION,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  MYSQL_USER: process.env.MYSQL_USER,
  MYSQL_REGION: process.env.MYSQL_REGION,
  MYSQL_PROXY_HOST: process.env.MYSQL_PROXY_HOST,
  MYSQL_PORT: process.env.MYSQL_PORT,
};
